// flow-typed signature: 99eb4937011140965fca4e50a1ba38fa
// flow-typed version: <<STUB>>/babel-plugin-react-relay_v^0.9.3-3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-relay/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-relay/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-relay/lib/index'>;
}
